import { SavedPattern } from "@/types";

export const starterPatterns: SavedPattern[] = [
  {
    id: "email",
    pattern: "[\\w.+-]+@[\\w-]+\\.[\\w.]+",
    flags: "gi",
    label: "Email address",
    description: "Basic email format validator",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: "url",
    pattern: "https?:\\/\\/[^\\s/$.?#][^\\s]*",
    flags: "gi",
    label: "URL",
    description: "Matches http and https URLs",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: "iso-date",
    pattern: "\\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])",
    flags: "g",
    label: "ISO date",
    description: "Date in YYYY-MM-DD format",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: "hex-color",
    pattern: "#(?:[0-9a-fA-F]{3}){1,2}\\b",
    flags: "gi",
    label: "Hex color",
    description: "CSS hex color with hash",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: "ipv4",
    pattern: "(?:\\d{1,3}\\.){3}\\d{1,3}",
    flags: "g",
    label: "IPv4 address",
    description: "Standard IPv4 address",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: "phone",
    pattern: "\\+?[\\d\\s().\\-]{7,20}",
    flags: "g",
    label: "Phone number",
    description: "International phone format",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: "html-tag",
    pattern: "<\\/?[a-z][a-z0-9]*(?:\\s[^>]*)?>",
    flags: "gi",
    label: "HTML tag",
    description: "Any HTML opening or closing tag",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: "semver",
    pattern: "v?\\d+\\.\\d+\\.\\d+(?:-[\\w.]+)?",
    flags: "g",
    label: "Semantic version",
    description: "semver format x.y.z",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: "credit-card",
    pattern: "(?:\\d{4}[\\s-]?){3}\\d{4}",
    flags: "g",
    label: "Credit card",
    description: "Major card number formats",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: "uuid",
    pattern: "[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}",
    flags: "gi",
    label: "UUID",
    description: "Standard UUID v4 format",
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
];